title: Kent Maps DofE
tagline: Duke of Edinburgh award site
banner: https://picsum.photos/id/403/1000/400?blur=1
favicon: /images/favicon.svg

# When using a custom domain these fields must be updated to match
# the account, repository name and branch (ref)
acct: kent-map
repo: dofe
ref: main

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: About
  icon: info
  path: /about
- label: Contact Us
  icon: envelope
  path: "/contact-us"

# If the /contact-us path is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
contactForm:
  toEmail:
  - ron.snyder@ithaka.org
  subject: Kent DofE Contact

#######################################################
# Base URL of server used for serving and optionally
# creating IIIF presentation manifests
######################################################
iiifServer: https://iiif.juncture-digital.org

siteAdmins:
- rsnyder

######################################################
# Optional credentials used for GitHub API and OAuth integration
######################################################

# GitHub upscoped API token used for content retrivals
#ghUnscopedToken: <Base64 encoded GitHub unscoped token>

# Google Cloud OAuth settings for GithHub login via Juncture
#gcAuthDomain: <Base64-encoded Google Cloud OAuth domain>
#gcApiKey: <Base64-encoded restricted access Google Cloud API key>
